import Footer from "@/components/footer";
import Header from "@/components/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// Layout file automatically gets created when we run the app, even though if deleted because its mandatory

// page.js file present in the app folder becomes a children when layout.js renders.

// The nearest page.js file within the same directory as this layout.js will be rendered as the children prop. If there are multiple page.js files in nested folders, each layout.js only wraps the page.js in its own directory or subdirectories.
